apiVersion: kro.run/v1alpha1
kind: Workload
metadata:
  name: podinfo
  namespace: workloads
spec:
  image: ghcr.io/stefanprodan/podinfo:6.7.0
  port: 9898
  replicas: 2
  readinessPath: /readyz
  livenessPath: /healthz
  cpuRequest: 100m
  memoryRequest: 64Mi
  cpuLimit: 200m
  memoryLimit: 128Mi
